# action.yml
name: "gh xml to md action"
description: "Greet someone and record the time"
inputs:
  path_to_junit_xml:
    description: "Path to the to be converted junit xml"
    required: true
    default: ""
  output_path:
    description: "Path to the expected result file"
    required: true
    default: ""
  output_name:
    description: "Name of the expected result file"
    required: true
    default: "converted"
outputs:
  path_to_generated_md:
    description: "The path to the generated markdown file"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path_to_junit_xml }}
    - ${{ inputs.output_path }}
    - ${{ inputs.output_name }}
