# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  path-to-junit-xml:
    description: "Path to the to be converted junit xml"
    required: true
    default: ""
  upload-to-wiki:
    description: "Shall the action upload to the repo.wiki"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.upload-to-wiki }}
