on: [push]

jobs:
  plain-convert-cfg:
    runs-on: ubuntu-latest
    name: A job to test xml2md conversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch xml convert 2 md
        id: convert
        uses: ./
        with:
          path_to_junit_xml: "./data/result.xml"
          upload_to_wiki: "false"
      # Check the output
      - name: get result value
        run: echo "The time was ${{ steps.convert.outputs.path_to_generated_md }}"
      # Cat the output
      - name: Cat result file
        run: ls -al /home/runner
        # Cat the output
      - name: Cat result file
        run: cat /home/runner/converted.md
  upload-config:
    runs-on: ubuntu-latest
    name: A job to test xml2md conversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch xml convert 2 md
        id: convert
        uses: ./
        with:
          path_to_junit_xml: "./data/result.xml"
          upload_to_wiki: "true"
      # Check the output
      - name: get result value
        run: echo "The time was ${{ steps.convert.outputs.path_to_generated_md }}"
      # Cat the output
      - name: Cat result file
        run: ls -al /home/runner
        # Cat the output
      - name: Cat result file
        run: cat /home/runner/converted.md
