on: [push]

jobs:
  plain-convert-cfg:
    runs-on: ubuntu-latest
    name: A job to test xml2md conversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch xml convert 2 md
        id: hello
        uses: ./
        with:
          path-to-junit-xml: "Here"
          upload-to-wiki: "false"
  upload-config:
    runs-on: ubuntu-latest
    name: A job to test xml2md conversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch xml convert 2 md
        id: convert
        uses: ./
        with:
          path-to-junit-xml: "./data/result.xml"
          upload-to-wiki: "true"
      # Check the output
      - name: Get the output time
        run: echo "The time was ${{ steps.convert.outputs.path-to-generated-md }}"
