on: [push]

jobs:
  plain-convert-cfg:
    runs-on: ubuntu-latest
    name: A job to test xml2md conversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch xml convert 2 md
        id: convert
        uses: ./
        with:
          path_to_junit_xml: "./data/result.xml"
      - name: PWD
        run: pwd
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: ./
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GPAT_PRIVATE }}
