on: [push]

jobs:
  plain-convert-cfg:
    runs-on: ubuntu-latest
    name: A job to test xml2md conversion
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set failure string
        if: ${{ failure() }}
        id: fail
        run: echo "::set-output name=name::failing-"

      - name: Set success string
        if: ${{ success() }}
        id: success
        run: echo "::set-output name=name::success-"

      - name: Fetch xml convert 2 md
        id: convert
        uses: mholetzko/gh-junit-xml-to-markdown@v1.1
        with:
          path_to_junit_xml: "./data/result.xml"
          output_path: "./out"
          output_name: "${{ steps.success.outputs.name }}${{ steps.fail.outputs.name }}${{ steps.date.outputs.date }}"
          gh_action_url: "www.google.com"

      - name: Check outdir
        run: ls -al ./out

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: ./out
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GPAT_PRIVATE }}
